version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.2.1
  kube-orb: circleci/kubernetes@0.11.2

executors:
  ci-base:
    docker:
      - image: cimg/base:stable
  machine:
    machine: true

jobs:
  deploy:
    executor: ci-base
    steps:
      - kube-orb/install-kubectl
      - checkout
      - run:
          name: Deploy
          command: chmod +x setup.sh; ./setup.sh --name-space=istio-system
     
workflows:
  build-and-deploy:
    jobs:
      - deploy