version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.2.1
  kubernetes: circleci/kubernetes@0.11.2

# Pipeline parameters
parameters:
  # These pipeline parameters are required by the "trigger-integration-tests-workflow"
  # job, by default.
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"

executors:
  ci-base:
    docker:
      - image: cimg/base:stable

  machine:
    machine: true

  minikube:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      CHANGE_MINIKUBE_NONE_USER=true

  macos:
    macos:
      xcode: "10.1.0"

commands:
  start-minikube:
    steps:
      - run:
          name: Start minikube
          command: |
            sudo apt-get update
            sudo apt-get install -y conntrack
            curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
              && chmod +x minikube
            sudo cp minikube /usr/local/bin && rm minikube
            sudo -E minikube start --vm-driver=none --cpus 2 --memory 2048
  integration-tests:
    steps:
      - checkout
      - kubernetes/install
      - run:
          name: Test kops
          command: kops version
      - run:
          name: Test kubectl
          command: kubectl
      - kubernetes/install-kubeconfig:
          kubeconfig: MY_KUBECONFIG_DATA
      - run:
          name: Test kubeconfig output
          command: |
            [[ -f $HOME/.kube/config && ! -z $HOME/.kube/config && $(<$HOME/.kube/config) == "test" ]]
  integration-tests-specific-version:
    steps:
      - checkout
      - kubernetes/install:
          kubectl-version: v1.15.2
          kops-version: 1.12.2
      - run:
          name: Test kops version
          command: kops version | grep "1.12.2"
      - run:
          name: Test kubectl version
          command: |
            set +e
            # ignore connection refused error
            KUBECTL_VERSION=$(kubectl version)
            set -e
            echo $KUBECTL_VERSION | grep "v1.15.2"
      - kubernetes/install-kubeconfig
      - run:
          name: Test kubeconfig output
          command: |
            [[ -f $HOME/.kube/config && ! -z $HOME/.kube/config && $(<$HOME/.kube/config) == "test" ]]

jobs:
  integration-test-docker:
    executor: ci-base
    environment:
      # For testing the install-kubeconfig command
      MY_KUBECONFIG_DATA: dGVzdA==
    steps:
      - integration-tests

  integration-test-machine:
    executor: machine
    environment:
      # For testing the install-kubeconfig command
      KUBECONFIG_DATA: dGVzdA==
    steps:
      - integration-tests-specific-version

  integration-test-macos:
    executor: macos
    environment:
      # For testing the install-kubeconfig command
      MY_KUBECONFIG_DATA: dGVzdA==
    steps:
      - integration-tests

  integration-test-kubectl:
    executor: minikube
    steps:
      - checkout
      - kubernetes/install-kubectl
      - start-minikube
      - kubernetes/create-or-update-resource:
          resource-file-path: "tests/nginx-deployment/deployment.yaml"
          resource-name: "deployment/nginx-deployment"
          get-rollout-status: true
          show-kubectl-command: true
      - kubernetes/update-container-image:
          resource-name: "deployment/nginx-deployment"
          container-image-updates: "nginx=nginx:1.9.1 redis=redis:5-buster"
          record: true
      - kubernetes/get-rollout-status:
          resource-name: "deployment/nginx-deployment"
          watch-rollout-status: true
      - kubernetes/rollback:
          resource-name: "deployment/nginx-deployment"
          get-rollout-status: true
      - kubernetes/delete-resource:
          resource-types: "deployments"
          resource-names: "nginx-deployment"
          now: true
          wait: true
      - kubernetes/create-or-update-resource:
          resource-file-path: "tests/kustomize/overlays/staging"
          resource-name: "deployment/staging-hello"
          kustomize: true
          get-rollout-status: true
          show-kubectl-command: true
      - kubernetes/delete-resource:
          resource-file-path: "tests/kustomize/overlays/staging"
          kustomize: true
          now: true
          wait: true

workflows:

  integration-tests_prod-release:
    jobs:
      - integration-test-docker
      - integration-test-machine
      - integration-test-macos