version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.2.1
  kube-orb: circleci/kubernetes@0.11.2

jobs:
  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - kube-orb/install-kubectl
      - checkout
      - run:
          name: Deploy
          command: chmod +x setup.sh; ./setup.sh --name-space=istio-system

workflows:
  version: 2
  build-master:
    jobs:
      - deploy:
          filters:
            branches:
              only: master