name: "Create cluster using KinD"
on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
      - name: Cluster Info
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
      - name: Install ISTIO 
        run: |
          curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.9.1 sh - \
           && cd istio-1.9.1 && ls -l
          cp ./bin/istioctl /usr/local/bin/istioctl && chmod +x /usr/local/bin/istioctl
          export PATH=$PWD/bin:$PATH
          istioctl install --set profile=demo -y         
      - name: Deploy  
        run: |
          ls -l; chmod +x setup.sh
          ./setup.sh --name-space=istio-system --force
      - name: Test Installation  
        run: |
            echo "Create namespace with ISTIO sidecar"
            kubectl apply -f example/SmallStep-mutual/namespace.yaml 
            echo "Create simple application deployment"
            kubectl apply -f example/SmallStep-mutual/httpbin.yaml 
            echo "Create ISTIO gateway and virtual service"
            kubectl apply -f example/SmallStep-mutual/httpbin-gateway.yaml
            echo "Create certificate"
            kubectl apply -f example/SmallStep-mutual/Certificate.yaml
            echo "Check, that certificate successfully issued"
            kubectl get certificates.cert-manager.io -n istio-system
            STATUS=$(kubectl get certificates.cert-manager.io -n istio-system httpbin-m-certificate -o json | jq -r '.status.conditions[].status')
            if [[ "$STATUS" != "True"  ]]
            then
            echo "Something is going wrong. Please investigate: kubectl describe stepissuers.certmanager.step.sm -n $NAME_SPACE "
            else
            echo "We are OK."
            fi       
